#
# Spring Boot Application Configuration
# (https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
#

# Shows what Spring Boot autodetection is actually doing
debug: true

#
# Logging
# (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html)
#
logging:
    file: /var/log/app/spring.log
    level:
        root: INFO
        # This is cool to check which method is called for a specific GET request
        org.springframework.web: DEBUG
