global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

# Scape means that Prometheus pulls data from the given target ports
scrape_configs:

  # Prometheus should report its internal metrics to itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Gather hardware and Linux kernel statistics using the Prometheus "node-exporter" Daemon
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Gather SpringBoot Actuator metrics
  - job_name: 'springboot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']
