version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
      ports:
        - "14269"                   # 
        - "127.0.0.1:14268:14268"             # accept jaeger.thrift directly from clients
        - "14267"                   # 
        - "14250"                   # accept model.proto
        - "127.0.0.1:9411:9411"               # Zipkin compatible endpoint (optional)
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "127.0.0.1:16686:16686"             # serve frontend
        - "16687"                   # 
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "127.0.0.1:5775:5775/udp"           # accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
        - "127.0.0.1:6831:6831/udp"           # accept jaeger.thrift over compact thrift protocol
        - "127.0.0.1:6832:6832/udp"           # accept jaeger.thrift over binary thrift protocol
        - "127.0.0.1:5778:5778"               # serve configs
      restart: on-failure
      depends_on:
        - jaeger-collector

    cassandra:
      image: cassandra:3.9

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      depends_on:
        - cassandra
      # ports: 7000-7001/tcp, 7199/tcp, 9042/tcp, 9160/tcp

#    app1:
#      image: "de.lathspell.test/app1:latest"
